### ISSUE TITLE
Crashing at starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [TibiNonEst/cauldron-dyeing#2]
https://bytebin.lucko.me/nvLOJYFbBQ

**Comment by violet-sh** [comment]
Argh okay yeah, I changed the mappings and it worked in my testing but it seems that my mixins to synthetic methods are failing.

**Comment by violet-sh** [comment]
Thank you for alerting me to this, I didn't realize that these mixins would behave the way they did with synthetic methods. Oh well, I guess that just means I need to actually test in production and not just a dev environment before making a release. I'll have a fixed release out in a few mins hopefully.
