### ISSUE TITLE
[Suggestion] Bedrock features!

### ISSUE THREAD

**Issue by Nekkok** [TibiNonEst/cauldron-dyeing#8]
Hi! It would be possible for you to make it compatible with the potion mechanics of bedrock? Also, it would be cool if in top of that depending on what you throw on them (glowstone dust, redstone, fermented spider eyes, gunpowder and dragon's breath) the liquid properties could change so you could craft different types of potions with it. And for an extra addition, milk cauldrons could heal you and emptying the cauldron when standing on them.

Sorry because I know this maybe unfair to ask because it's a lot, but you're the only mod creator on Fabric working with the vanilla cauldron these days. Anyway, thank you!

**Comment by violet-sh** [comment]
I'm not opposed to expanding this mod to potions, but mods like [Bedrockify](https://modrinth.com/mod/bedrockify) already fulfill this niche (and most everything else Bedrock). For now, I think I'm going to keep it limited to its original color-only functionality.
