### ISSUE TITLE
Sodium 0.5 Compatibility

### ISSUE THREAD

**Issue by LokeYourC3PH** [TibiNonEst/cauldron-dyeing#9]
Since Sodium 0.5, compatibility has been broken. There's like three mods currently causing incompat. issues for me: Cauldron Dyeing, Fluid Void Fading and Cull Leaves.

Please look into this :)

**Comment by violet-sh** [comment]
I was actually looking into this yesterday but got distracted by other stuff, it'll be fixed soon:tm:!
